name: Run Unit Test and Lint Check

on: 
  pull_request:
    branches:
      - main
      - master
      - 'release/**'

jobs:  
  #First job
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Node modules
        run: yarn ci

      - name: Linting
        run: yarn lint

      - name: Unit & Integration tests
        run: yarn test:ci
        
      - name: Generate coverage
        run: yarn test:ci:tee

      - name: Jest Coverage Comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          badge-title: Coverage
          coverage-title: My Coverage Title
          coverage-path: ./coverage/coverage.txt

      - name: Check the output coverage
        run: |
          echo "Summary Report"
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary Html - ${{ steps.coverageComment.outputs.summaryHtml }}"

          echo "Coverage Report"
          echo "lines - ${{ steps.coverageComment.outputs.lines }}"
          echo "branches - ${{ steps.coverageComment.outputs.branches }}"
          echo "functions - ${{ steps.coverageComment.outputs.functions }}"
          echo "statements - ${{ steps.coverageComment.outputs.statements }}"
          echo "coverage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "color - ${{ steps.coverageComment.outputs.color }}"
          echo "Coverage Html - ${{ steps.coverageComment.outputs.coverageHtml }}"
  # Second Job
  build-android:
    needs: install-and-test
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
        
